
---CREATION OF DATABASE----

CREATE DATABASE EMP_MANAGEMENT;
USE EMP_MANAGEMENT;

---CREATION OF TABLES---

CREATE TABLE EMP_DET
(EID CHAR(5),NAME VARCHAR(50), GENDER CHAR(1), DOB DATE, ADDRESS VARCHAR(50), CITY VARCHAR(30), PHONE CHAR(10),
EMAIL_ID VARCHAR(100));

CREATE TABLE EMP_ROLE
(EID CHAR(5), DEPT VARCHAR(20), DESIGNATION VARCHAR(50), SALARY INT);

---CREATION OF PROCEDURE FOR INSERTION OF DATAS---

CREATE PROCEDURE INS_DATA (@ID AS CHAR(5), @N AS VARCHAR(50), @G AS CHAR(1), @DB AS DATE, @ADD AS VARCHAR(50),
							@C AS VARCHAR(30), @PH AS CHAR(10), @EM AS VARCHAR(100),@DPT AS VARCHAR(20),
							@DSI AS VARCHAR(50), @SAL AS INT)
AS
BEGIN

			INSERT INTO EMP_DET
			VALUES(@ID,@N,@G,@DB,@ADD,@C,@PH,@EM);

			INSERT INTO EMP_ROLE
			VALUES(@ID,@DPT,@DSI,@SAL);

			SELECT * FROM EMP_DET;
			SELECT * FROM EMP_ROLE;

END;

---INSERTION OF CONSTRAINTS----

ALTER TABLE EMP_DET
ALTER COLUMN EID CHAR(5) NOT NULL;
ALTER TABLE EMP_DET
ADD CONSTRAINT UNQ UNIQUE(PHONE);
ALTER TABLE EMP_DET
ADD CONSTRAINT CHK CHECK (DOB !> '31 DECEMBER 2000');
ALTER TABLE EMP_DET
ADD CONSTRAINT PK PRIMARY KEY (EID);
ALTER TABLE EMP_ROLE
ADD CONSTRAINT FK FOREIGN KEY (EID) REFERENCES EMP_DET(EID);

---INSERTION OF DATAS---

INS_DATA 'E0001', 'AAKAASH KUMAR', 'M', '19 MAY 1998', '12/2, RAMAN NADAR COLONY, PARK STREET', 'NAGERCOIL', 
			'8892389500', 'AAKASH@GMAIL.COM','SALES', 'ASSOCIATE', '24000';
INS_DATA 'E0002', 'AJAY KUMAR', 'M', '06 JULY 1996', '5/A, 6TH SHARON PARK, KUMARANKOIL STREET', 'NAGERCOIL', 
			'9973896790', 'AJKUMAR@GMAIL.COM','SALES', 'ASSOCIATE', '24000';
INS_DATA 'E0003', 'BERLIN ABI', 'F', '19 JUNE 1997', 'FOLLIE APARTMENTS', 'VALLIYOOR', 
			'7998249178', 'ABINAYA@GMAIL.COM','TELECOM', 'ASSOCIATE', '28500';
INS_DATA 'E0004', 'BERLIN JOHN', 'M', '23 NOVEMBER 1989', 'P.K.D COLONY', 'KARUNGAL', 
			'9785648950', 'BJOHN@GMAIL.COM','SALES', 'SENIOR ASSOCIATE', '45000';
INS_DATA 'E0005', 'BIJU ANTONY', 'M', '19 MAY 1996', 'P.N. NADAR TOWN', 'TIRUNELVELI', 
			'9803478920', 'BIJU@YAHOO.COM','ADMINISTRATION', 'SENIOR ADMIN', '48700';
INS_DATA 'E0006', 'CHRISTINE MATHEW', 'F', '05 OCTOBER 1998', 'RAJAS FLATS,PUTHUKUDIYERUPPU', 'NAGERCOIL', 
			'8896748790', 'CHRISTMATHEW@YAHOO.COM','IT DESK', 'TRAINEE', '20000';
INS_DATA 'E0007', 'DHIVYA KUMARI', 'F', '08 OCTOBER 1993', '5TH CROSS STREET,PARK COLONY', 'CHENNAI', 
			'8836989900', 'DHIVYA@GMAIL.COM','ADMINISTRATION', 'ASSOCIATE', '32000';
INS_DATA 'E0008', 'EZHIL SUBRAMANIAM', 'M', '10 APRIL 1989', 'SAALIGRAMAM', 'CHENNAI', 
			'9556892780', 'EZHILSUBBU@HOTMAIL.COM','TELECOM', 'TEAM LEAD', '67000';
INS_DATA 'E0009', 'GANESH THIRUMOORTHY', 'M', '21 FEBRUARY 1988', '3/3C RAJAN STREET, KAMARAJAR COLONY', 'TIRUNELVELI', 
			'9827483880', 'GANESH@YAHOO.COM','IT DESK', 'ASSOCIATE', '25000';
INS_DATA 'E0010', 'HARSHINI', 'F', '21 JUNE 1992', '303C/2D, PARK STREET,RAMANPUTHUR', 'NAGERCOIL', 
			'9675678420', 'HARSH@GMAIL.COM','IT DESK', 'ASSOCIATE', '25000';

---ADDING COLUMNS TO TABLE---

ALTER TABLE EMP_ROLE
ADD DOJ DATE;

UPDATE EMP_ROLE SET DOJ = '23 OCTOBER 2020'
WHERE EID IN('E0001','E0002','E0006');

UPDATE EMP_ROLE SET DOJ = '12 DECEMBER 2019'
WHERE EID IN('E0003','E0005');

UPDATE EMP_ROLE SET DOJ = '05 APRIL 2014'
WHERE EID IN('E0004','E0008','E0009');

UPDATE EMP_ROLE SET DOJ = '25 OCTOBER 2018'
WHERE EID IN('E0007','E0010');

SELECT * FROM EMP_DET;
SELECT * FROM EMP_ROLE;

ALTER TABLE EMP_ROLE
ADD PF INT, HRA INT;

UPDATE EMP_ROLE SET PF = SALARY*.09, HRA = SALARY*.15;

--CREATION OF PROCEDURE FOR INSERTION OF NEW EMPLOYEES AND CALCULATING THEIR PF AND HRA--

CREATE PROCEDURE PF_HRA_NEW (@ID AS CHAR(5), @N AS VARCHAR(50), @G AS CHAR(1), @DB AS DATE, @ADD AS VARCHAR(50),
							@C AS VARCHAR(30), @PH AS CHAR(10), @EM AS VARCHAR(100),@DPT AS VARCHAR(20),
							@DSI AS VARCHAR(50), @SAL AS INT, @DJ AS DATE)
AS
BEGIN
			DECLARE @P AS INT;
			DECLARE @HR AS INT;

			SET @P = @SAL*.09;
			SET @HR = @SAL*.15;
			
			INSERT INTO EMP_DET
			VALUES(@ID,@N,@G,@DB,@ADD,@C,@PH,@EM);

			INSERT INTO EMP_ROLE
			VALUES(@ID,@DPT,@DSI,@SAL,@DJ,@P,@HR);

			SELECT * FROM EMP_DET;
			SELECT * FROM EMP_ROLE;

END;

PF_HRA_NEW 'E0011', 'INDHUJA KRISHNAN', 'F', '07 MARCH 1998', '44A/4, AISHWARYA GARDEN', 'COIMBATORE','9923198490',
			'INDHU@OUTLOOK.COM', 'TELECOM', 'ASSOCIATE', '28000', '21 JANUARY 2020';



---DISPLAYING TABLES USING SUB-QUERIES---

SELECT EID,NAME,GENDER, CITY, EMAIL_ID FROM EMP_DET
WHERE EID IN(SELECT EID FROM EMP_ROLE WHERE DEPT = 'IT DESK');

SELECT * FROM EMP_DET;
SELECT * FROM EMP_ROLE;

---CREATION OF CORPORATE MAIL ID FOR EMPLOYEES USING FUNCTION :

CREATE FUNCTION CORP_MAIL (@ID AS CHAR(5),@N AS VARCHAR(20),@D AS VARCHAR(20))
RETURNS VARCHAR(100)
AS
BEGIN

			DECLARE @EM AS VARCHAR(100);
			DECLARE @LN AS INT;
			DECLARE @S AS INT;
			DECLARE @LL AS VARCHAR(5);

			SET @LN = LEN(@N);
			SET @S = CHARINDEX(' ', @N);
			SET @LL = SUBSTRING(RIGHT(@N,@LN-@S),1,2);
			SET @EM = CONCAT(LEFT(@N,2),@LL,RIGHT(@ID,2),'@',@D,'.COM');

			RETURN @EM;

END;

---CREATION OF CORPORATE MAIL IDS IN THE TABLE :

ALTER TABLE EMP_DET
ADD  CORP_MAIL_ID VARCHAR(100);

UPDATE EMP_DET SET CORP_MAIL_ID = CONCAT(LEFT(NAME,2),SUBSTRING(RIGHT(NAME,LEN(NAME)-CHARINDEX(' ',NAME)),1,2),
								  RIGHT(EID,2),'@CORPORATE','.COM');

SELECT * FROM EMP_DET;
SELECT * FROM EMP_ROLE;

--CREATION OF VIEWS FOR RESTRICTING SOME DATAS :

CREATE VIEW EMP_DETAILS
AS
		SELECT E1.EID,NAME,GENDER,CITY,PHONE,DEPT,DESIGNATION,SALARY,DOJ,PF,HRA
		FROM EMP_DET E1
		INNER JOIN EMP_ROLE E2
		ON E1.EID = E2.EID;

SELECT * FROM EMP_DETAILS;




